server:
  port: '8091'
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/f6?createDatabaseIfNotExist=true
    password: root  # DdCya995142@4681
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: 'false'
logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG